### ISSUE TITLE
about openpose model

### ISSUE THREAD

**Issue by kyriefeng** [felixchenfy/Realtime-Action-Recognition#46]
how can i choose the model of openpose during training？
the default is mobilenet_thin！
i wanna to compare accuracy using different models

**Comment by felixchenfy** [comment]
In the [config file](https://github.com/felixchenfy/Realtime-Action-Recognition/blob/master/config/config.yaml), see this paragraph:
```
openpose:
      model: mobilenet_thin
      img_size: 656x368
      # model: cmu
      # img_size: 432x368
```
You can comment out line 1&2, and uncomment line 3&4.

Currently, there are only these 2 models.
